FROM nginx:alpine

# Copia os teus ficheiros do portal (HTML, CSS, JS) para a pasta do Nginx
COPY . /usr/share/nginx/html/

# Copia o teu ficheiro nginx.conf personalizado para dentro do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]