services:
  db:
    image: postgres:15
    container_name: opspulse-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=opspulse
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/opspulse/postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: opspulse-api
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=opspulse
    depends_on:
      - db

  portal:
    build:
      context: ./frontend
      dockerfile: Dockerfile.portal
    container_name: opspulse-portal
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    container_name: opspulse-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SERVER_DOMAIN=localhost
    ports:
      - "3000:3000"
    volumes:
      - /root/grafana_data:/var/lib/grafana

  data-generator:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: opspulse-data-generator
    restart: unless-stopped
    command: ["python", "data_generator.py"]
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=opspulse
      - DATA_GENERATOR_INTERVAL=10
    depends_on:
      - db